server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: service-manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.55/drug?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    max-active: 100
    max-wait: 100000
    timeout: 0




mybatis:
  mapper-locations: classpath:mapper/*.xml
