server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: tree-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.101.55:3306/drug?characterEncoding=utf-8&serverTimezone=UTC&tcpRcvBuf=1024000
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mybatis/mapper-*.xml
