server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: provider
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gfgd?characterEncoding=utf-8
    username: root
    password:
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:OrderMapper/*.xml