server:
  port: 7005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: login-feign
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    encode: UTF-8
    timeout: 6000
thymeleaf:
  encoding: UTF-8
  servlet:
    content-type: text/html
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1






