server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: order-feign

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html


hystrix:

  command:

    default:

      execution:

        isolation:

          thread:

            timeoutInMilliseconds: 5000
