server:
  port: 5001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: order-feign
  main:    #可以多个使用生产者
    allow-bean-definition-overriding: true
  data:
    mongodb:
       host: 127.0.0.1
       port: 27017
       database: meng



    #mongodb
     # application:
     #   name: pring-boot-mongodb

