server:
  port: 5002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
   # url: jdbc:mysql://192.168.101.55:3306/drug?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/drugb?useUnicode=true&characterEncoding=utf-8
    # url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: root

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html

mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  #typeAliasesPackage: com.gugr.springboot.entity
  type-aliases-package: com.jk.pojo

  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



